# Load packages and define sigmoid function

In [46]:
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split

def sigmoid(x):
    return 1 / (1 + tf.math.exp(-x))

# Load the dataset (iris with only two classes)

In [47]:
data = pd.read_csv("iris.csv")
data

sepal_length  sepal_width  petal_length  petal_width  class
0            5.1          3.5           1.4          0.2      0
1            4.9          3.0           1.4          0.2      0
2            4.7          3.2           1.3          0.2      0
3            4.6          3.1           1.5          0.2      0
4            5.0          3.6           1.4          0.2      0
..           ...          ...           ...          ...    ...
95           5.7          3.0           4.2          1.2      1
96           5.7          2.9           4.2          1.3      1
97           6.2          2.9           4.3          1.3      1
98           5.1          2.5           3.0          1.1      1
99           5.7          2.8           4.1          1.3      1

[100 rows x 5 columns]

# Split dataset into training/testing sets

In [48]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, :-1], data.iloc[:, -1], test_size=0.3)
X_train = tf.cast(tf.convert_to_tensor(X_train), tf.float32)
X_test = tf.cast(tf.convert_to_tensor(X_test), tf.float32)
y_train = tf.cast(tf.convert_to_tensor(y_train), tf.float32)
y_test = tf.cast(tf.convert_to_tensor(y_test), tf.float32)

train = tf.data.Dataset.from_tensor_slices((X_train, y_train))
test = tf.data.Dataset.from_tensor_slices((X_test, y_test))

# Initialize variables

In [49]:
weights = tf.random.uniform((1, X_train.shape[1]), minval=0.0001, maxval=0.001)
bias = tf.random.uniform((1, 1), minval=0.0001, maxval=0.001)
eta = 0.001

weights

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0.00077405, 0.00088458, 0.0002309 , 0.00075721]], dtype=float32)>

# Perform logistic regression, updating the variables at each point

In [50]:
runs = 5
for i in range(runs):
    # iterate and update at each value
    train = train.shuffle(len(train))
    for x, y in train:
        y_i = sigmoid(tf.tensordot(weights, x, 1) + bias)

        dw = x * (y_i - y)
        db = y_i - y

        weights = weights - eta * dw
        bias = bias - eta * db

weights

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[ 0.00381271, -0.08971262,  0.18218699,  0.07538848]],
      dtype=float32)>

# Evaluate test set and calculate error rate

In [51]:
errors = 0
for x, y in test:
    y_i = 1 if sigmoid(tf.tensordot(weights, x, 1) + bias) >= 0.5 else 0

    if y_i != y:
        errors += 1

errors / len(test)

0.16666666666666666